---
- name: deloy nginx
  hosts: nginx
  gather_facts: False
  remote_user: root
  roles:
    - nginx

- name: deloy mysql
  hosts: mysql
  gather_facts: False
  remote_user: root
  roles:
    - mysql

- name: deloy php
  hosts: php
  gather_facts: False
  remote_user: root
  roles:
    - php

---
- name: tranfer nginx yum source
  template:
    src: 'nginx.repo'
    dest: '/etc/yum.repos.d/nginx.repo'

- name: yum install nginx
  yum:
    name: nginx
    state: latest

- name: setting nginx
  template:
    src: nginx.j2
    dest: /etc/nginx/conf.d/default.conf
  notify:
    - restart nginx

- name: set index.php
  template:
    src: index.j2
    dest: /usr/share/nginx/html/index.html


---
- name: tranfer mysql yum source
  template:
    src: 'mysql.repo'
    dest: '/etc/yum.repos.d/mysql.repo'

- name: yum install mysql
  yum:
    name: [mysql-community-server, MySQL_python]
    state: latest

- name: transfer j2
  template:
    src: gpassword.j2
    dest： $HOME/gpassword.sh

- name: bash shell to change inital password
  shell: 'bash $HOME/gpassword.sh'

- name: remove shell scripts
  shell: 'rm -rf $HOME/gpassword.sh'


---
- name: transfer php yum source
  template:
    src: php.repo
    dest: /etc/yum.repos.d/php.repo

- name: yum install php
  yum:
    name: [php, php-fpm, php-devel, php-mbstring, php-scrypt, php-gd, php-mysql, php-xml]
    state: latest
  notify:
    - started php-fpm